window.FORM_LIBRARY = {
  "hyrox_male": {
    "id": "hyrox_male",
    "name": "HYROX Readiness - Male",
    "sport": "HYROX",
    "gender": "Male",
    "asymmetryThreshold": 12,
    "scoreBand": {
      "build": 50,
      "develop": 70,
      "ready": 85
    },
    "segments": [
      {
        "id": "mobility_msk",
        "title": "Mobility / MSK",
        "abbr": "MOB",
        "summary": "Movement quality and screening tests that influence running mechanics, squat depth, lunge positions and loading tolerance."
      },
      {
        "id": "strength_capacity",
        "title": "Strength Capacity",
        "abbr": "STR",
        "summary": "Force-frame strength qualities across hip, knee, calf and shoulder. This segment highlights force deficits and left-right asymmetry."
      },
      {
        "id": "power_force",
        "title": "Power / Force Production",
        "abbr": "PWR",
        "summary": "Jump and force-rate qualities that influence transitions, acceleration, repeated ground contacts and fatigue resistance."
      },
      {
        "id": "hyrox_engine",
        "title": "HYROX Engine",
        "abbr": "HYX",
        "summary": "Sport-specific simulation tests covering running, ski erg, wall balls, burpee broad jumps and lunges."
      }
    ],
    "tests": [
      {
        "id": "hip_internal_rotation",
        "category": "MSK Screening - Objective",
        "name": "Hip Internal Rotation",
        "unit": "Degrees",
        "min": 30.0,
        "max": 45.0,
        "type": "Bilateral - with Asym",
        "left": 30.0,
        "right": 30.0,
        "weight": 3.0,
        "icon": "HIP",
        "explanation": "Hip rotation helps absorb load while running, lunging and changing position under fatigue.",
        "segment": "mobility_msk"
      },
      {
        "id": "hip_external_rotation",
        "category": "MSK Screening - Objective",
        "name": "Hip External Rotation",
        "unit": "Degrees",
        "min": 30.0,
        "max": 45.0,
        "type": "Bilateral - with Asym",
        "left": 28.0,
        "right": 15.0,
        "weight": 3.0,
        "icon": "HIP",
        "explanation": "Supports squat depth, lunge control and stable lower-limb mechanics.",
        "segment": "mobility_msk"
      },
      {
        "id": "hip_flexor_length",
        "category": "MSK Screening - Objective",
        "name": "Hip Flexor Length",
        "unit": "Degrees",
        "min": 5.0,
        "max": 0.0,
        "type": "Bilateral - with Asym",
        "left": 15.0,
        "right": 10.0,
        "weight": 3.0,
        "icon": "HIP",
        "explanation": "Affects stride mechanics, trunk position and lunge efficiency.",
        "segment": "mobility_msk"
      },
      {
        "id": "rectus_femoris_length",
        "category": "MSK Screening - Objective",
        "name": "Rectus Femoris Length",
        "unit": "Degrees",
        "min": 60.0,
        "max": 90.0,
        "type": "Bilateral - with Asym",
        "left": 60.0,
        "right": 65.0,
        "weight": 3.0,
        "icon": "QUAD",
        "explanation": "Influences knee drive, lunge tolerance and anterior thigh loading.",
        "segment": "mobility_msk"
      },
      {
        "id": "df_lunge",
        "category": "MSK Screening - Objective",
        "name": "DF Lunge",
        "unit": "CM",
        "min": 10.0,
        "max": 14.0,
        "type": "Bilateral - with Asym",
        "left": 13.0,
        "right": 13.0,
        "weight": 3.0,
        "icon": "ANK",
        "explanation": "Critical for squats, lunges, running mechanics and fatigue-position control.",
        "segment": "mobility_msk"
      },
      {
        "id": "cet",
        "category": "MSK Screening - Subjective",
        "name": "CET",
        "unit": "",
        "min": null,
        "max": null,
        "type": "Unilateral",
        "overall": "Negative",
        "weight": 0,
        "icon": "MSK",
        "explanation": "Screens neural or symptom sensitivity that may affect loading tolerance during training.",
        "segment": "mobility_msk"
      },
      {
        "id": "slump_test",
        "category": "MSK Screening - Subjective",
        "name": "Slump Test",
        "unit": "",
        "min": null,
        "max": null,
        "type": "Unilateral",
        "overall": "Negative",
        "weight": 0,
        "icon": "NEU",
        "explanation": "Screens neural sensitivity that may influence running comfort and posterior-chain loading.",
        "segment": "mobility_msk"
      },
      {
        "id": "hip_flexion",
        "category": "Force Frame Tests",
        "name": "Hip - Flexion",
        "unit": "Newton",
        "min": 250.0,
        "max": 350.0,
        "type": "Bilateral - with Asym",
        "left": 228.0,
        "right": 228.0,
        "weight": 2.0,
        "icon": "HIP",
        "explanation": "Supports running posture, knee drive and repeated lunge recovery.",
        "segment": "strength_capacity"
      },
      {
        "id": "hip_adduction",
        "category": "Force Frame Tests",
        "name": "Hip - Adduction",
        "unit": "Newton",
        "min": 300.0,
        "max": 400.0,
        "type": "Bilateral - with Asym",
        "left": 331.0,
        "right": 353.0,
        "weight": 2.0,
        "icon": "ADD",
        "explanation": "Supports pelvic control, running stability and lateral load tolerance.",
        "segment": "strength_capacity"
      },
      {
        "id": "hip_abduction",
        "category": "Force Frame Tests",
        "name": "Hip - Abduction",
        "unit": "Newton",
        "min": 300.0,
        "max": 400.0,
        "type": "Bilateral - with Asym",
        "left": 362.0,
        "right": 370.0,
        "weight": 2.0,
        "icon": "ABD",
        "explanation": "Helps maintain knee alignment and pelvis control under fatigue.",
        "segment": "strength_capacity"
      },
      {
        "id": "hip_extension",
        "category": "Force Frame Tests",
        "name": "Hip -Extension",
        "unit": "Newton",
        "min": 350.0,
        "max": 550.0,
        "type": "Bilateral - with Asym",
        "left": 652.0,
        "right": 700.0,
        "weight": 2.0,
        "icon": "EXT",
        "explanation": "Key driver of propulsion for running and posterior-chain output.",
        "segment": "strength_capacity"
      },
      {
        "id": "knee_flexion",
        "category": "Force Frame Tests",
        "name": "Knee Flexion",
        "unit": "Newton",
        "min": 150.0,
        "max": 250.0,
        "type": "Bilateral - with Asym",
        "left": 147.0,
        "right": 176.0,
        "weight": 2.0,
        "icon": "KNE",
        "explanation": "Important for running durability, deceleration and knee protection.",
        "segment": "strength_capacity"
      },
      {
        "id": "knee_extension",
        "category": "Force Frame Tests",
        "name": "Knee Extension",
        "unit": "Newton",
        "min": 250.0,
        "max": 400.0,
        "type": "Bilateral - with Asym",
        "left": 489.0,
        "right": 468.0,
        "weight": 2.0,
        "icon": "KNE",
        "explanation": "Supports wall balls, lunges, running and repeated knee-dominant work.",
        "segment": "strength_capacity"
      },
      {
        "id": "ham_quads_ratio",
        "category": "Force Frame Tests",
        "name": "Ham : Quads Ratio",
        "unit": "Ratio",
        "min": 0.6,
        "max": 1.0,
        "type": "Bilateral - without Asym",
        "left": 0.3006134969,
        "right": 0.3760683761,
        "weight": 2.0,
        "icon": "H:Q",
        "explanation": "Shows posterior/anterior balance and running durability risk.",
        "segment": "strength_capacity"
      },
      {
        "id": "plantar_flexion",
        "category": "Force Frame Tests",
        "name": "Plantar Flexion",
        "unit": "Newton",
        "min": 750.0,
        "max": 1200.0,
        "type": "Bilateral - with Asym",
        "left": 552.0,
        "right": 598.0,
        "weight": 2.0,
        "icon": "CALF",
        "explanation": "Supports running economy, ankle stiffness and ground contact tolerance.",
        "segment": "strength_capacity"
      },
      {
        "id": "shoulder_ir",
        "category": "Force Frame Tests",
        "name": "Shoulder IR",
        "unit": "Newton",
        "min": 130.0,
        "max": 250.0,
        "type": "Bilateral - with Asym",
        "left": 154.0,
        "right": 131.0,
        "weight": 2.0,
        "icon": "IR",
        "explanation": "Supports upper-body force transfer and repeated wall-ball positions.",
        "segment": "strength_capacity"
      },
      {
        "id": "shoulder_er",
        "category": "Force Frame Tests",
        "name": "Shoulder ER",
        "unit": "Newton",
        "min": 110.0,
        "max": 200.0,
        "type": "Bilateral - with Asym",
        "left": 147.0,
        "right": 154.0,
        "weight": 2.0,
        "icon": "ER",
        "explanation": "Supports overhead control, shoulder tolerance and efficient wall-ball mechanics under fatigue.",
        "segment": "strength_capacity"
      },
      {
        "id": "counter_movement_jumps",
        "category": "Force Decks Tests",
        "name": "Counter Movement Jumps",
        "unit": "W/Kg",
        "min": 47.0,
        "max": 63.0,
        "type": "Unilateral",
        "overall": 40.0,
        "weight": 3.0,
        "icon": "JMP",
        "explanation": "Reflects lower-body explosiveness and neuromuscular readiness.",
        "segment": "power_force"
      },
      {
        "id": "imtp_rfd",
        "category": "Force Decks Tests",
        "name": "IMTP_RFD",
        "unit": "N/S",
        "min": 1200.0,
        "max": 3200.0,
        "type": "Unilateral",
        "overall": 575.0,
        "weight": 5.0,
        "icon": "RFD",
        "explanation": "Shows how quickly force can be produced for transitions and stations.",
        "segment": "power_force"
      },
      {
        "id": "grip_strength",
        "category": "Dynamo",
        "name": "Grip Strength",
        "unit": "Newton",
        "min": 343,
        "max": 588,
        "type": "Bilateral - with Asym",
        "left": 372.0,
        "right": 411.0,
        "weight": 8.0,
        "icon": "GRP",
        "explanation": "Matters for ski erg, carries, pulling tasks and fatigue resistance.",
        "segment": "strength_capacity"
      },
      {
        "id": "12_min_run",
        "category": "Hyrox Simulation Test",
        "name": "12 Min Run",
        "unit": "Meters",
        "min": 2050.0,
        "max": 2750.0,
        "type": "Unilateral",
        "overall": 1385.0,
        "weight": 15.0,
        "icon": "RUN",
        "explanation": "Estimates aerobic engine and running durability for HYROX.",
        "segment": "hyrox_engine"
      },
      {
        "id": "500_m_ski_erg",
        "category": "Hyrox Simulation Test",
        "name": "500 m Ski Erg",
        "unit": "Seconds",
        "min": 135.0,
        "max": 200.0,
        "type": "Unilateral",
        "overall": 122.0,
        "weight": 8.5,
        "icon": "SKI",
        "explanation": "Reflects upper-body pulling power, trunk stiffness and aerobic power.",
        "segment": "hyrox_engine"
      },
      {
        "id": "1_5_min_wallball",
        "category": "Hyrox Simulation Test",
        "name": "1.5 Min Wallball",
        "unit": "Reps",
        "min": 20.0,
        "max": 30.0,
        "type": "Unilateral",
        "overall": 18.0,
        "weight": 8.5,
        "icon": "WB",
        "explanation": "Tests repeated squat-to-throw capacity and breathing control.",
        "segment": "hyrox_engine"
      },
      {
        "id": "1_5_min_burpee_distance",
        "category": "Hyrox Simulation Test",
        "name": "1.5 Min Burpee Distance",
        "unit": "Meters",
        "min": 15.0,
        "max": 30.0,
        "type": "Unilateral",
        "overall": 21.0,
        "weight": 8.5,
        "icon": "BBJ",
        "explanation": "Reflects total-body repeat power under high fatigue.",
        "segment": "hyrox_engine"
      },
      {
        "id": "1_5_min_lunge_distance",
        "category": "Hyrox Simulation Test",
        "name": "1.5 Min Lunge Distance",
        "unit": "Meters",
        "min": 20.0,
        "max": 38.0,
        "type": "Unilateral",
        "overall": 32.0,
        "weight": 8.5,
        "icon": "LUN",
        "explanation": "Shows unilateral endurance, trunk control and leg capacity.",
        "segment": "hyrox_engine"
      }
    ]
  }
};
